version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
     - '23000:3000'
    volumes:
     - ./data/grafana:/var/lib/grafana
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nh-cafe
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '23306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '20080:80'
volumes:
  db-data:
    driver: local
  grafana-data:
    driver: local