version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
     - '23000:3000'
    volumes:
     - ./data/grafana:/var/lib/grafana
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${NH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nh-cafe
      MYSQL_USER: ${NH_MYSQL_USER}
      MYSQL_PASSWORD: ${NH_MYSQL_PASSWORD}
    # ports:
    #   - '23306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: https://nhcafe-pma.ashiwawa.com
    ports:
      - '20080:80'
  nhcafe-bo:
    image: nhcafe-bo
    container_name: nhcafe_bo
    restart: always
    ports:
      - '29001:9001'